### ISSUE TITLE
Why does Network-Fix have less FLOPs and Params

### ISSUE THREAD

**Issue by ShoufaChen** [yanwei-li/DynamicRouting#12]
Hi, 

Thank you very much for your reply and help so many times.

In the paper,
> Firstly, all of the paths in the routing space are fixed with no difference to formulate our baseline, namely the ‘Fix’

Does it mean that all the routes in the network will be active?  If so, I think `Network-Fix`  has more FLOPs and Params than `Dynamic-A,B,C`, which is  incompatible with the results presented in Talbe 4.

Please point it out if there is something I understand in a wrong way.

**Comment by yanwei-li** [comment]
Hi! If all the paths are 'fixed' in the network, all of the gates in each node will be droped to save resources (because all the paths will be open), which bring less params and FLOPs. 
And if given no resource constraint, gates will be included, and most of the paths would tend to be preserved to achieve better performance. 
This brings the cost gap between two different settings.
Hope this could solve your confusion.

**Comment by ShoufaChen** [comment]
Thanks and it solves my confusion definitely.
